; Tripwire Receiver (central node)
[env:heltec_wifi_lora_32_V3]
platform = espressif32
board = heltec_wifi_lora_32_V3
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbserial-6
monitor_port = /dev/cu.usbserial-6
lib_deps = jgromes/RadioLib@^6.6.0